minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@entwico/*'

allowBuilds:
  esbuild: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    'eslint-plugin-jsx-a11y>eslint': '10'
